config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root 'home#index'

  resources :users, only: [:new, :create, :edit, :update, :show, :destroy] do
    get :activate, on: :member
  end

  resources :user_sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:create, :edit, :update]

  get 'login' => 'user_sessions#new', as: :login
  delete 'logout' => 'user_sessions#destroy', as: :logout
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  
  validates :password, length: { minimum: 3 }, if: -> { new_record? || crypted_password_changed? }
  # the confirmation setting checks whether the password and password_confirmation match
  validates :password, confirmation: true, if: -> { new_record? || crypted_password_changed? }
  validates :password_confirmation, presence: true, if: -> { new_record? || crypted_password_changed? }

  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login

  private
  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :require_login
  
  def index
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  skip_before_action :require_login
    
  # request password reset.
  # you get here when the user entered his email in the reset password form and submitted it.
  def create 
    @user = User.find_by_email(params[:email])
        
    # This line sends an email to the user with instructions on how to reset their password (a url with a random token)
    @user.deliver_reset_password_instructions! if @user
        
    # Tell the user instructions have been sent whether or not email was found.
    # This is to not leak information to attackers about which emails exist in the system.
    redirect_to(root_path, :notice => 'Instructions have been sent to your email.')
  end
    
  # This is the reset password form.
  def edit
    @token = params[:id]
    @user = User.load_from_reset_password_token(params[:id])

    if @user.blank?
      not_authenticated
      return
    end
  end
      
  # This action fires when the user has sent the reset password form.
  def update
    @token = params[:id]
    @user = User.load_from_reset_password_token(params[:id])

    if @user.blank?
      not_authenticated
      return
    end

    # the next line makes the password confirmation validation work
    @user.password_confirmation = params[:user][:password_confirmation]
    # the next line clears the temporary token and updates the password
    if @user.change_password!(params[:user][:password])
      redirect_to(root_path, :notice => 'Password was successfully updated.')
    else
      render :action => "edit"
    end
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(root_path, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(root_path, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create, :activate]

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to(root_path, notice: 'Registration successfull. Check your email for activation instructions.')
    else
      render action: 'new'
    end
  end

  def update
    @user = User.find(params[:id])

      if @user.update(user_params)
        redirect_to(@user, notice: 'User was successfully updated.')
      else
        render action: 'edit'
      end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to(root_path)
  end

  def activate
    if @user = User.load_from_activation_token(params[:id])
      @user.activate!
      redirect_to(login_path, notice: 'User was successfully activated.')
    else
      not_authenticated
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/home/index.html.haml
%h2 Hello World
%p
  The time is now: #{Time.now}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Corondefy
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %div
      - if current_user
        = link_to 'Edit Profile', edit_user_path(current_user.id)
        = link_to 'Log out', logout_path, method: :delete
      - else
        = link_to 'Register', new_user_path
        |
        \#{link_to 'Login', :login} |
    %div
      %p#notice= flash[:notice]
      %p#alert= flash[:alert]
    = yield

app/views/password_resets/create.html.haml
%h1 PasswordResets#create
%p Find me in app/views/password_resets/create.html.haml

app/views/password_resets/edit.html.haml
%h1 Choose a new password
= form_for @user, :url => password_reset_path(@token), :html => {:method => :put} do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :email
    %br/
    = @user.email
  .field
    = f.label :password
    %br/
    = f.password_field :password
  .field
    = f.label :password_confirmation
    %br/
    = f.password_field :password_confirmation
  .actions
    = f.submit

app/views/password_resets/update.html.haml
%h1 PasswordResets#update
%p Find me in app/views/password_resets/update.html.haml

app/views/user_sessions/_forgot_password_form.html.haml
= form_with url: password_resets_path, method: :post, local: true do |f|
  .field
    = f.label :email
    %br/
    = f.text_field :email
    = f.submit "Reset my password!"

app/views/user_sessions/_form.html.haml
= form_with url: user_sessions_path, method: :post, local: true do |f|
  .field
    = f.label :email
    %br/
    = f.text_field :email
  .field
    = f.label :password
    %br/
    = f.password_field :password
  .actions
    = f.submit "Login"
  %div
    = f.label "keep me logged in"
    %br/
    = f.check_box :remember

app/views/user_sessions/edit.html.haml
%h1 Editing user_session
= render 'form'
= link_to 'Show', @user_session
|
\#{link_to 'Back', root_path}

app/views/user_sessions/new.html.haml
%h1 Login
= render 'form'
%h1 Forgot Password?
= render 'forgot_password_form'
= link_to 'Back', root_path

app/views/users/_form.html.haml
= form_with model: @user, local: true do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :email
    %br/
    = f.text_field :email
  .field
    = f.label :password
    %br/
    = f.password_field :password
  .field
    = f.label :password_confirmation
    %br/
    = f.password_field :password_confirmation
  .actions
    = f.submit

app/views/users/edit.html.haml
%h1 Editing user
= render 'form'
= link_to 'Show', @user
|
\#{link_to 'Back', root_path}

app/views/users/index.html.haml
%h1 Listing users
%table
  %tr
    %th User
    %th
    %th
    %th
  - @users.each do |user|
    %tr
      %td= user.email
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete
%br/
= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user
= render 'form'
= link_to 'Back', root_path

app/views/users/show.html.haml
%p
  %b User:
  = @user.email
= link_to 'Edit', edit_user_path(@user)
|
\#{link_to 'Back', root_path}